### ISSUE TITLE
Browse - Loading mods freeze

### ISSUE THREAD

**Issue by The10-thDoctor** [LeeTwentyThree/SubnauticaModManager#6] opened 2023-01-21 14:25 UTC
Hello, I seem to have a problem,
I know a simingly indentical issue was already solved, but the solution provided doesn't work.
It's no use deleting the Temp folder in the SNModManager folder
Thx for future answer
![Capture d’écran 2023-01-21 152309](https://user-images.githubusercontent.com/123251991/213871145-5cc32fb8-6824-49bb-b78e-84c890dce6eb.png)

**Comment by LeeTwentyThree** [comment] 2023-01-21 17:38
Do you have slow/choppy internet by any chance? I think the timeout is pretty low for the image loading so if it takes too long that could happen.  Can’t really say for sure unless you send a log file right after that happens

**Comment by kiararey** [comment] 2023-01-21 18:32
I'm having the same issue! No choppy internet
<img width="1646" alt="Screenshot 2023-01-21 at 12 30 39 PM" src="https://user-images.githubusercontent.com/24264174/213881798-72d89e86-5744-4828-992b-1a44de84b5a2.png">

**Comment by LeeTwentyThree** [comment] 2023-01-22 02:17
Personally my log file can be found at `C:\Users\kevin\AppData\LocalLow\Unknown Worlds\Subnautica\Player.log`. Send it if you can, please.

**Comment by LeeTwentyThree** [comment] 2023-01-22 02:18
Personally my log file can be found at `C:\Users\USER_NAME_HERE\AppData\LocalLow\Unknown Worlds\Subnautica`. Send that if you can, otherwise there's a million things it could be.

**Comment by guid118** [comment] 2023-01-24 13:46
I have the same problem on windows 10, no choppy internet either.
BepInEx gave me this:
`[Error  : Unity Log] Exception: Failed WebPGetFeatures with error VP8_STATUS_BITSTREAM_ERROR
In WebP.Decode
Stack trace:
SubnauticaModManager.Web.Images.WebP.Decode (System.Byte[] rawWebP, SubnauticaModManager.Web.Images.WebPDecoderOptions options, System.Drawing.Imaging.PixelFormat pixelFormat) (at <dd5124d0f7884d56a68d417790ee2585>:0)
SubnauticaModManager.Web.Images.ImageCache+<GetOrAddWebpToCache>d__5.MoveNext () (at <dd5124d0f7884d56a68d417790ee2585>:0)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <bd0d47c27bd84106afaaecc2c74cdb94>:0)`

**Comment by LeeTwentyThree** [comment] 2023-01-24 15:20
I really cannot find any cause for this. It seems to be something related to either connection to the Submodica servers or invalid encoding/decoding, both of which are extremely difficult to look into. Thanks for the information, though. Since the cause is still entirely unknown, I believe I can release an update so that mods that couldn’t load their images just use a default icon instead.

**Comment by Punkfou** [comment] 2023-01-24 21:38
Same problem. I hope that can help you ![Modmanager](https://user-images.githubusercontent.com/48484847/214426282-22bc75b2-39e4-48f1-a27e-c47af9028b2f.png)

**Comment by The10-thDoctor** [comment] 2023-01-25 15:31
Ok, sorry for the wait time. So, I don't have slow internet so I don't think it's the cause.
And here is my Player.log file, hoping it can help : [Player.log](https://github.com/LeeTwentyThree/SubnauticaModManager/files/10500793/Player.log)

**Comment by LeeTwentyThree** [comment] 2023-01-26 00:28
Working on an update. Version 1.0.6 coming soon

**Comment by LeeTwentyThree** [comment] 2023-01-26 02:51
Resolved in [version 1.0.6](https://github.com/LeeTwentyThree/SubnauticaModManager/releases/tag/1.0.6).

**Closed by LeeTwentyThree** 2023-01-26 02:51 UTC
Labels: bug, not enough info
